-- AlterTable
ALTER TABLE "public"."FoodItem"
ADD COLUMN "healthLight" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "isLiquid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "pinyinCode" TEXT,
ADD COLUMN "thumbImageUrl" TEXT;

-- AlterTable
ALTER TABLE "public"."FoodNutrition"
ADD COLUMN "calciumMg" DOUBLE PRECISION,
ADD COLUMN "cholesterolMg" DOUBLE PRECISION,
ADD COLUMN "copperMg" DOUBLE PRECISION,
ADD COLUMN "folateMcg" DOUBLE PRECISION,
ADD COLUMN "gi" DOUBLE PRECISION,
ADD COLUMN "gl" DOUBLE PRECISION,
ADD COLUMN "ironMg" DOUBLE PRECISION,
ADD COLUMN "magnesiumMg" DOUBLE PRECISION,
ADD COLUMN "manganeseMg" DOUBLE PRECISION,
ADD COLUMN "niacinMg" DOUBLE PRECISION,
ADD COLUMN "phosphorusMg" DOUBLE PRECISION,
ADD COLUMN "potassiumMg" DOUBLE PRECISION,
ADD COLUMN "riboflavinMg" DOUBLE PRECISION,
ADD COLUMN "saturatedFatG" DOUBLE PRECISION,
ADD COLUMN "seleniumUg" DOUBLE PRECISION,
ADD COLUMN "sugarG" DOUBLE PRECISION,
ADD COLUMN "thiamineMg" DOUBLE PRECISION,
ADD COLUMN "vitaminAUg" DOUBLE PRECISION,
ADD COLUMN "vitaminB6Mg" DOUBLE PRECISION,
ADD COLUMN "vitaminCMg" DOUBLE PRECISION,
ADD COLUMN "vitaminEMg" DOUBLE PRECISION,
ADD COLUMN "zincMg" DOUBLE PRECISION;

-- CreateIndex
CREATE INDEX "FoodItem_pinyinCode_idx" ON "public"."FoodItem"("pinyinCode");
